### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by markvdb** [wil-ldf-ire/tribe#2]
Hello, 

As a FOSDEM organiser, I just found https://linuxfr.org/users/misc/journaux/tout-le-monde-ou-plutot-trop-de-gens-continue-de-se-foutre-des-licences-en-2023 in my news feed. The author presented the lack of a clearly visible free/open source license for your project as a symptom of FOSDEM not being very careful about FOSS licensing. He doesn't seem to have followed up with you though.

Could you please add a clearly visible license to your project?

Thank you!

Mark
FOSDEM vzw

P.S. Enjoy speaking at FOSDEM 2023!

**Comment by cityowltypes** [comment]
Hi Mark,
Thank you for pointing us to the forum and raising an issue here on github. We'll resolve it in the next 2 days. We'll add a license.

Akshay

**Comment by cityowltypes** [comment]
Hi Mark, we have updated all Tribe related repositories with licenses. All backend libraries with GNU GPL v3, front-end ones with MIT and a content related one with CC. If there's anything else, let me know. I'll close this issue in a day or two. Thanks again for informing.

**Comment by markvdb** [comment]
Thank you very much for your fast and effective reaction. Enjoy FOSDEM!

M

**Comment by JeromeMartinez** [comment]
> All backend libraries with GNU GPL v3, front-end ones with MIT 

great! Now the corresponding code is FOSS.

> and a content related one with CC

I don't find the repo(s) with the "CC" license, which one is it?
It is not possible to know if the project is FOSS without checking the whole content of the project, and "CC" is not a license, it is a group of license, and some of the "CC" licenses (the ones with ND or NC) are not FOSS.

**Comment by cityowltypes** [comment]
Hi @JeromeMartinez
Repository is https://github.com/wil-ldf-ire/types.json/
The license is CC BY-SA 4.0
The license is compatible with GNU GPL v3.
